"""updating tables and relationships

Revision ID: 178d755fd331
Revises: d7ce5e1fdf5f
Create Date: 2025-07-14 18:03:13.359711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178d755fd331'
down_revision: Union[str, None] = 'd7ce5e1fdf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
