"""update donations  table change name from created at to donated at and delete updated_at colomn 

Revision ID: 2f9ad4b67885
Revises: 4c6a006095a4
Create Date: 2025-07-12 21:32:28.631608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9ad4b67885'
down_revision: Union[str, None] = '4c6a006095a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donated_at', sa.DateTime(), nullable=True))
    op.drop_column('donations', 'updated_at')
    op.drop_column('donations', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('donations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('donations', 'donated_at')
    # ### end Alembic commands ###
