"""adding two more coloums in installment table fine and total ammount to pay for clearity

Revision ID: 735f49be6ffa
Revises: 178d755fd331
Create Date: 2025-07-15 14:39:50.227506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735f49be6ffa'
down_revision: Union[str, None] = '178d755fd331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('fine_amount', sa.Float(), nullable=True))
    op.add_column('installments', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'total_amount')
    op.drop_column('installments', 'fine_amount')
    # ### end Alembic commands ###
