"""updating tables and relationships

Revision ID: d7ce5e1fdf5f
Revises: e4a6bc2c99dc
Create Date: 2025-07-14 17:41:35.326374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7ce5e1fdf5f'
down_revision: Union[str, None] = 'e4a6bc2c99dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('loan_id', sa.Integer(), nullable=True))
    op.add_column('fines', sa.Column('installment_id', sa.Integer(), nullable=True))
    op.add_column('fines', sa.Column('fine_amount', sa.Float(), nullable=True))
    op.add_column('fines', sa.Column('days_late', sa.Integer(), nullable=True))
    op.alter_column('fines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'fines', 'loans', ['loan_id'], ['id'])
    op.create_foreign_key(None, 'fines', 'installments', ['installment_id'], ['id'])
    op.drop_column('fines', 'reason')
    op.drop_column('fines', 'updated_at')
    op.drop_column('fines', 'amount')
    op.add_column('installments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('installments', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('installments', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('installments', sa.Column('paid_date', sa.DateTime(), nullable=True))
    op.alter_column('installments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'installments', 'users', ['user_id'], ['id'])
    op.drop_column('installments', 'remaining_installments')
    op.drop_column('installments', 'total_monthly_payment')
    op.drop_column('installments', 'end_date')
    op.drop_column('installments', 'created_at')
    op.drop_column('installments', 'loan_ammount')
    op.drop_column('installments', 'start_date')
    op.alter_column('loans', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('loans', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('loans', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('loans', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('installments', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('loan_ammount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('installments', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('total_monthly_payment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('remaining_installments', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'installments', type_='foreignkey')
    op.alter_column('installments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('installments', 'paid_date')
    op.drop_column('installments', 'due_date')
    op.drop_column('installments', 'amount')
    op.drop_column('installments', 'user_id')
    op.add_column('fines', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fines', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('fines', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fines', type_='foreignkey')
    op.drop_constraint(None, 'fines', type_='foreignkey')
    op.alter_column('fines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('fines', 'days_late')
    op.drop_column('fines', 'fine_amount')
    op.drop_column('fines', 'installment_id')
    op.drop_column('fines', 'loan_id')
    # ### end Alembic commands ###
