"""updating installmentb table

Revision ID: e4a6bc2c99dc
Revises: 2f9ad4b67885
Create Date: 2025-07-13 12:55:49.952330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a6bc2c99dc'
down_revision: Union[str, None] = '2f9ad4b67885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('loan_ammount', sa.Float(), nullable=False))
    op.add_column('installments', sa.Column('remaining_installments', sa.Integer(), nullable=False))
    op.add_column('installments', sa.Column('status', sa.String(), nullable=False))
    op.add_column('installments', sa.Column('total_monthly_payment', sa.Float(), nullable=False))
    op.add_column('installments', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('installments', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.drop_column('installments', 'updated_at')
    op.drop_column('installments', 'paid_at')
    op.drop_column('installments', 'due_date')
    op.drop_column('installments', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('installments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('installments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('installments', 'end_date')
    op.drop_column('installments', 'start_date')
    op.drop_column('installments', 'total_monthly_payment')
    op.drop_column('installments', 'status')
    op.drop_column('installments', 'remaining_installments')
    op.drop_column('installments', 'loan_ammount')
    # ### end Alembic commands ###
