"""adding one colum in fine table status for clearity

Revision ID: f4b345dd59ea
Revises: 735f49be6ffa
Create Date: 2025-07-15 15:23:20.811305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b345dd59ea'
down_revision: Union[str, None] = '735f49be6ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fines', 'status')
    # ### end Alembic commands ###
